# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples
on:
  pull_request_target:

name: format-suggest.yaml

permissions: read-all

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Format
        run: air format .

      - name: Suggest
        uses: reviewdog/action-suggester@v1
        with:
          level: error
          fail_level: error
          tool_name: air
