# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples
on:
  pull_request_target:

name: format-suggest.yaml

permissions:
  pull-requests: write

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Format
        run: air format .

      - name: Suggest
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: air
